### ISSUE TITLE
Improve support for AWS SDK v3

### ISSUE THREAD

**Issue by mattfysh** [aws/aws-xray-sdk-node#547]
In the recent release of the Node.js v18 runtime on Lambda, the embedded SDK has been upgraded to v3: https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/

The current state of v3 support in aws-xray-sdk-node appears to be rather patchy. e.g. 
1. Much of the command data no longer appears in the trace
2. Wrapping most clients with `captureAWSv3Client` throws TypeScript errors. In fact, the only client I've found that works without a TS error is `AWSXRay.captureAWSv3Client(new S3Client({}))`

I was wondering if the team were aware of the shift to v3 in the latest lambda runtime environmnent, and whether this may translate to improved support for v3 by the Xray SDK? Thanks for reading!

**Comment by adambiggs** [comment]
We really need better X-Ray support for SDK v3. Especially since [ADOT is currently borderline unusable](https://github.com/aws-observability/aws-otel-lambda/issues/228), despite it being recommended at the top of `README.md`...

**Comment by willarmiros** [comment]
Hello,

Thanks for raising this issue, I'll try to address both issues:

> Much of the command data no longer appears in the trace

This is unfortunately a limitation of the AWS SDK v3 itself. The V3 middleware exposes much less data than v2 did, and as such our instrumentation can only read the basic attributes you see today. This limitation exists in ADOT as well, and I would suggest opening an issue against the aws-sdk-js-v3 repo to suggest exposing this info more readily.

> Wrapping most clients with captureAWSv3Client throws TypeScript errors

This is a known issue and #449 was an attempt to fix it, but unfortunately there were issues with the fix and we were not able to prioritize it since. Once we are able to take another look we can track it here.

**Comment by bilalq** [comment]
@RanVaknin [commented](https://github.com/aws/aws-sdk-js-v3/issues/4902#issuecomment-1618880864) • 

>Hi @bilalq ,
>
>JS SDK v3 exposes the same exact parameters that v2 does, the only difference is that those parameters are accessible via the middleware stack, which will require the Xray team to make adjustments on how the Xray clients accesses the data.
>
>Im sorry to ping pong you around back to the Xray team, but I did have a conversation with their PM @willarmiros (who now is no longer at Amazon) on March 2023, about this issue and had proven that all the relevant info is available via middleware stack.
>
>Since there's no action needed from the JS SDK team so Im going to close this. I encourage you to open the same feature request in [their repo](https://github.com/aws/aws-xray-sdk-node), so it can get traction and prioritized.
>
>All the best,
>Ran~

**Comment by bilalq** [comment]
Hey, @carolabadeer. Given the performance issues with OpenTelemetry noted in [this comment](https://github.com/aws/aws-sdk-js-v3/issues/4902#issuecomment-1624468569), would you consider making the changes to capture additional metadata in the traces here?

**Comment by bilalq** [comment]
This would also improve the usability of the [Powertools library](https://github.com/aws-powertools/powertools-lambda-typescript) maintained by AWS, as that is built on top of the X-Ray Node SDK.

**Comment by SchollSimon** [comment]
> @RanVaknin [commented](https://github.com/aws/aws-sdk-js-v3/issues/4902#issuecomment-1618880864) •
> 
> > Hi @bilalq ,
> > JS SDK v3 exposes the same exact parameters that v2 does, the only difference is that those parameters are accessible via the middleware stack, which will require the Xray team to make adjustments on how the Xray clients accesses the data.
> > Im sorry to ping pong you around back to the Xray team, but I did have a conversation with their PM @willarmiros (who now is no longer at Amazon) on March 2023, about this issue and had proven that all the relevant info is available via middleware stack.
> > Since there's no action needed from the JS SDK team so Im going to close this. I encourage you to open the same feature request in [their repo](https://github.com/aws/aws-xray-sdk-node), so it can get traction and prioritized.
> > All the best,
> > Ran~

 @carolabadeer @willarmiros so what's the status here? We really need a better support on AWS SDKv3 for Xray it is nearly unusable in its current state. It would help our company a lot if we get an solution soon.

**Comment by vinicius91carvalho** [comment]
For me here, I included it wrapping all of aws-sdk v3 clients, but the main issue is that it requires "aws-sdk" in the runtime, forcing me to add it on the build only for this dep.

**Comment by SchollSimon** [comment]
> For me here, I included it wrapping all of aws-sdk v3 clients, but the main issue is that it requires "aws-sdk" in the runtime, forcing me to add it on the build only for this dep.

How is this related to the issue aka access of data from the middleware stack?

**Comment by carolabadeer** [comment]
Hi all - happy to share with all of you that support for additional attributes in the AWS SDK v3 instrumentation has been [released in v3.5.2](https://github.com/aws/aws-xray-sdk-node/blob/master/CHANGELOG.md#352)! The newest version also includes the fix for the TS errors that would occur when using `captureAWSv3Client` ([released in 3.5.0](https://github.com/aws/aws-xray-sdk-node/blob/master/CHANGELOG.md#350))

Please check out the newest version and let us know if you are still running into any problems. Since the two issues reported initially have been addressed, I'll close out this issue as resolved!

**Comment by mnwk** [comment]
> 1. Much of the command data no longer appears in the trace
I think this still isn't fixed.

Using:
"@aws-sdk/client-dynamodb": "^3.568.0",
"aws-xray-sdk": "^3.6.0"
...
const client = AWSXRay.captureAWSv3Client(new DynamoDBClient({}));

I still don't get any data besides operation and tablename for a DynamoDB call.
